//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HossamAndHoda2021.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HossamAndHoda2021DBEntities : DbContext
    {
        public HossamAndHoda2021DBEntities()
            : base("name=HossamAndHoda2021DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactUsTBL> ContactUsTBL { get; set; }
        public virtual DbSet<OrderDetailTBL> OrderDetailTBL { get; set; }
        public virtual DbSet<OrderTBL> OrderTBL { get; set; }
        public virtual DbSet<ProductTBL> ProductTBL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserLoginTBL> UserLoginTBL { get; set; }
        public virtual DbSet<UserTBL> UserTBL { get; set; }
    }
}
