//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HossamAndHoda2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailTBL
    {
        public int OrderDetailID { get; set; }
        public Nullable<int> OrderIDD { get; set; }
        public Nullable<int> ProductIDD { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Price { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual OrderTBL OrderTBL { get; set; }
        public virtual ProductTBL ProductTBL { get; set; }
    }
}
