//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HossamAndHoda2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTBL()
        {
            this.OrderDetailTBL = new HashSet<OrderDetailTBL>();
        }
    
        public int ProductID { get; set; }
        public string ProductAutoCode { get; set; }
        public string ProductFactoryCode { get; set; }
        public string ProductNameAR { get; set; }
        public string ProductDetails { get; set; }
        public Nullable<int> ProductPrice { get; set; }
        public string ProductImage1URL { get; set; }
        public string ProductImage2URL { get; set; }
        public string ProductImage3URL { get; set; }
        public Nullable<int> ProductViews { get; set; }
        public Nullable<System.DateTime> DateOfMaking { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailTBL> OrderDetailTBL { get; set; }
    }
}
