//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HossamAndHoda2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginTBL
    {
        public int UserLoginID { get; set; }
        public Nullable<int> UserIDD { get; set; }
        public string LoginIPAddress { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string SessionUnique { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual UserTBL UserTBL { get; set; }
    }
}
